# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 082cb927a576501e4f54d8a833dd971ed04c6374b0a724b26a80c2bbc43fbb507cfefd2aedaf28da7dea88ca94be928f1c71bfa11774f5f2107aab32491fd71a

test:
  secret_key_base: 57b674990163628d6ee42cefc8fe040affef68ddf0064249cd4567477b5df900d8a09b5de0e5beadfeab95043d925da966db6e93e16ba72b474e0113dccc5a45

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
